myexe: myMain.o myStrFunc.o myMathFunc.o
	gcc -o myexe myMain.o myStrFunc.o myMathFunc.o
myMain.o: myMain.c
	gcc -c myMain.c
myMathFunc.o: myMathFunc.c
	gcc -c myMathFunc.c
myStrFunc.o: myStrFunc.c
	gcc -c myStrFunc.c
